# Page settings

baseurl = "http://dbparedes.github.io/"
languageCode = "en-us"
title = "David Paredes Website"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "David Paredes"
        tagline = "Prospective PhD Student"
        avatar = "david.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: db.paredes@gmail.com"
        title = "db.paredes@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:610-605-7595"
        title = "+610-605-7595"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//dbparedes.github.io"
        title = "dbparedes.github.io"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/dbparedes"
        title = "github.com/dbparedes"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/dparedes28"
        title = "@dparedes28"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Mechatronic Engineering"
        college = "Universidad Nacional de Ingenieria"
        dates = "2011 - 2015"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "Spanish"
        level = "Native"

        [[params.languages.list]]
        language = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Research Interests"

        [[params.interests.list]]
        interest = "Computer vision"

        [[params.interests.list]]
        interest = "Machine Learning"

        [[params.interests.list]]
        interest = "Deep Learning"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "About Me"
        summary = "I recently completed my B.S. with honors in mechatronics engineering at Universidad Nacional de Ingenieria in Lima, Peru. While I was undergrad I used to run and organize a student research group ([**GISCIA**](http://giscia.github.io)).\n\n I am currently working as a research intern at Siemens Healthineers. Previously, I had a great research experience at Duke University."
        # [GISCIA](http://giscia.github.io)
        #
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Research intern"
        dates = "2016/10- Present"
        company = "Siemens Healthineers - Malvern, PA"
        details = "I am working on applications of deep learning on medical imaging problems under the supervison of [Dr. Yiqiang Zhan](http://dblp.uni-trier.de/pers/hd/z/Zhan:Yiqiang)."


        [[params.jobs.list]]
        position = "Visiting Scholar"
        dates = "2016/01 - 2016/06"
        company = "Duke University - Durham, NC"
        details = "I was working under the supervision of [Prof. Maciej Mazurowski](http://deckard.duhs.duke.edu/~mazurowski/index.html) on fully automatic brain tumor segmentation using convolutional neural networks. Our paper has been accepted to **SPIE 2017**."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
